#!/bin/bash

FULL_AT=100
ICONS=("󰂎" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
CHARGING_ICON="󱐋"
is_charging=0
percentage=-1
bat_count=0
icon=""

while read -r line; do
	bat_charge=$(echo "$line" | grep -P -o '[0-9]+(?=%)')
	bat_count=$((bat_count + 1))
	percentage=$((percentage + bat_charge))
	if ((is_charging == 0)); then
		is_charging=$(echo "$line" | grep -q "Charging" && echo 1 || echo 0)
	fi
done < <(acpi -b)

percentage=$(((percentage / bat_count) * 100 / FULL_AT))
icon_index=$(awk -v percentage="$percentage" -v num_icons="${#ICONS[@]}" 'BEGIN {print int((percentage / 100) * (num_icons - 1))}')
icon="${ICONS[icon_index]}"
if ((is_charging == 1)); then
	icon="$icon$CHARGING_ICON"
fi

jq -ncM --argjson percentage "$percentage" --arg icon "$icon" \
	'{percentage: $percentage, icon: $icon}'
