#!/bin/bash

ETHERNET_ICON="󰈀 "
WIFI_ICONS=("󰤯 " "󰤟 " "󰤢 " "󰤨 ")
DISCONNECTED_ICON=" "

ethernet=$(nmcli device | grep ethernet)
ethernet_state=$(awk '{print $3}' <<<"$ethernet")
if [ "$ethernet_state" = "connected" ]; then
	connection=$(echo "$ethernet" | tr -s ' ' | cut -d' ' -f4-)
	connection=${connection%?}
	jq -ncM --arg connection "$connection" --arg icon "$ETHERNET_ICON" \
		'{"connection": $connection, icon: $icon}'
	exit
fi

wifi=$(nmcli device | grep wifi | head -1)
wifi_state=$(awk '{print $3}' <<<"$wifi")
if [ "$wifi_state" = "connected" ]; then
	connection=$(echo "$wifi" | tr -s ' ' | cut -d' ' -f4-)
	connection=${connection%?}
	signal=$(nmcli device wifi list | grep '\*' | tr -s ' ' | cut -d' ' -f8)
	icon_index=$(awk -v signal="$signal" -v num_icons="${#WIFI_ICONS[@]}" 'BEGIN {print int((signal / 100) * (num_icons - 1))}')
	icon="${WIFI_ICONS[icon_index]}"
	jq -ncM --arg connection "$connection" --arg icon "$icon" \
		'{"connection": $connection, "icon": $icon}'
	exit
fi

jq -ncM --arg icon "$DISCONNECTED_ICON" \
	'{"connection": "Disconnected", icon: $icon}'
