#!/bin/bash

ICON=" "
ACTIVE_ICON=" "

active_workspace=1

workspaces() {
	seq 1 10 | jq -scM --arg active "$active_workspace" --arg icon "$ICON" --arg active_icon "$ACTIVE_ICON" \
		'map({id: ., active: (. == ($active | tonumber)), icon: (if . == ($active | tonumber) then $active_icon else $icon end)})'
}

workspaces

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - |
	grep --line-buffered -e "^workspace>>" -e "^focusedmon>>" |
	while read -r line; do
		active_workspace=$(awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}' <<<"$line")
		workspaces
	done
