source "$ZDOTDIR/variables.zsh"
source "$ZDOTDIR/options.zsh"
source "$ZDOTDIR/aliases.zsh"
source "$ZDOTDIR/keybinds.zsh"
source "$ZDOTDIR/functions.zsh"
source "$ZDOTDIR/generate.zsh"
source "$ZDOTDIR/plugins.zsh"
