alias cat="bat"
alias cfg="git --git-dir=\$HOME/.dotfiles/ --work-tree=\$HOME"
alias ls="exa --icons --color=never"
alias nv="nvim"
alias pm="paru"
alias szsh="source \$ZDOTDIR/.zshrc"
alias wget="wget --hsts-file=\$XDG_DATA_HOME/wget-hsts"
alias py="python -q"
alias wf-recorder="wf-recorder -f $HOME/Videos/screenrecords/$(date +%Y%m%d_%H%M%S).mp4"
