#!/bin/bash

for monitor in $(swaymsg -t get_outputs | jq -r '.[].name'); do
	MONITOR=$monitor yambar &
done

swaymsg -m -t subscribe '[ "output" ]' | while read -r _; do
	killall yambar
	for monitor in $(swaymsg -t get_outputs | jq -r '.[].name'); do
		MONITOR=$monitor yambar &
	done
done
