#!/bin/bash

max_len=$(fd desktop "$XDG_DATA_HOME"/applications /usr/share/applications/ \
	--absolute-path \
	--exec awk '
        /^Name=/ {
            name = substr($0, index($0, "=") + 1)
						print(length(name))
        }
    ' '{}' \; | sort -nr | head -1)

application=$(
	fd desktop "$XDG_DATA_HOME"/applications /usr/share/applications/ \
		--absolute-path \
		--exec awk -v max_len="$max_len" '
        BEGIN { OFS = "\t" }
        /^Name=/ && !name { name = substr($0, index($0, "=") + 1) }
        /^Exec=/ && !exec { exec = substr($0, index($0, "=") + 1) } 
        END { printf("%-*s\t%s\t%s\n", max_len, name, exec, FILENAME) }
		' '{}' \; |
		sort -t$'\t' -k2,2 -u |
		sort -t$'\t' -k1,1 |
		"$XDG_CONFIG_HOME"/sway/scripts/fzfmenu -d '\\t' --with-nth=1..2 |
		cut -f3
)

[[ -n "$application" ]] && gio launch "$application"
