[notebook]
dir = "~/notes/"

[note]
language = "en"
default-title = "Untitled"
filename = "{{format-date now 'timestamp-unix'}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[format.markdown]
link-format = "wiki"
link-encode-path = false
link-drop-extension = false
hashtags = false
colon-tags = false
multiword-tags = false

[lsp.diagnostics]
wiki-title = "none"
dead-link = "error"

[group.idea.note]
filename = "{{slug title}}"
template = "idea.md"

[group.project.note]
filename = "{{slug title}}"
template = "project.md"

[group.study.note]
filename = "{{slug title}}"
template = "study.md"

[tool]
fzf-bind-new = ""
