notARepository: "quit"
gui:
  border: single
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: false
  showFileIcons: false
  showPanelJumps: false
  showRandomTip: false
  tabWidth: 2
  theme:
    activeBorderColor:
      - default
    inactiveBorderColor:
      - "#404040"
    searchingActiveBorderColor:
      - default
    optionsTextColor:
      - default
    selectedLineBgColor:
      - "#101010"
    inactiveViewSelectedLineBgColor:
      - "#101010"
    cherryPickedCommitFgColor:
      - default
    cherryPickedCommitBgColor:
      - default
    markedBaseCommitFgColor:
      - default
    markedBaseCommitBgColor:
      - default
    unstagedChangesColor:
      - "#404040"
    defaultFgColor:
      - default
  authorColors:
    "*": "#606060"
