#!/bin/bash

close_bars() {
	eww close bar --all
}

open_bars() {
	monitors=$(hyprctl monitors -j | jq 'length')
	for i in $(seq 0 $((monitors - 1))); do
		eww open bar --id "$i" --screen "$i"
	done
}

open_bars

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - |
	grep --line-buffered -e "^monitoradded>>" -e "^monitorremoved>>" |
	while read -r _; do
		close_bars
		open_bars
	done
