#!/bin/bash

type=$1
file=$2
width=$(($3 * 8))
height=$(($4 * 14))

case $type in
image) exec magick -- "$file"[0] -auto-orient -strip -scale "${width}x${height}>" - | img2sixel -S ;;
video) exec ffmpeg -loglevel quiet -i "$file" -frames:v 1 -ss 0.1 -vf "scale=$width:$height:force_original_aspect_ratio=decrease" -f image2pipe -vcodec png - | img2sixel -S ;;
pdf) exec pdftoppm -singlefile -png "$file" 2>/dev/null | magick - -scale "${width}x${height}>" png:- | img2sixel -S ;;
*) exit 1 ;;
esac
