battery: &battery
  poll-interval: 30000
  anchors:
    icon: &icon
      ramp:
        tag: capacity
        items:
          - string:
              text: 󰂎
          - string:
              text: 󰁺
          - string:
              text: 󰁻
          - string:
              text: 󰁼
          - string:
              text: 󰁽
          - string:
              text: 󰁾
          - string:
              text: 󰁿
          - string:
              text: 󰂀
          - string:
              text: 󰂁
          - string:
              text: 󰂂
          - string:
              text: 󰁹
  content:
    map:
      conditions:
        state == unknown:
          - <<: *icon
          - string:
              text: "{capacity}%"
              left-margin: 2
        state == discharging:
          - <<: *icon
          - string:
              text: "{capacity}%"
              left-margin: 2
        state == charging:
          - <<: *icon
          - string:
              text: 󱐋
          - string:
              text: "{capacity}%"
              left-margin: 2
        state == full:
          - <<: *icon
          - string:
              text: "{capacity}%"
              left-margin: 2
        state == "not charging":
          - <<: *icon
          - string:
              text: "{capacity}%"
              left-margin: 2

bar:
  monitor: "${MONITOR}"
  height: 25
  location: top
  spacing: 8
  margin: 10

  font: monospace:pixelsize=12:weight=bold

  foreground: A0A0A0FF
  background: 000000FF

  border:
    width: 1
    color: 404040FF
    margin: 10
    bottom-margin: 0

  left:
    - clock:
        time-format: "%H:%M"
        content:
          - string:
              text: 
          - string:
              text: "{time}"
              left-margin: 10

    - clock:
        date-format: "%a, %b %e"
        content:
          - string:
              text: 
          - string:
              text: "{date}"
              left-margin: 10

  center:
    - i3:
        spacing: 2
        persistent: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
        content:
          "":
            map:
              default:
                string:
                  text: " "
                  foreground: 404040FF
              conditions:
                state == focused || state == unfocused && output == "${MONITOR}":
                  string:
                    text: " "
                    foreground: A0A0A0FF

  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink" && ~muted:
                - ramp:
                    tag: cubic_volume
                    items:
                      - string:
                          text: 
                      - string:
                          text: 
                      - string:
                          text: 
                - string:
                    text: "{cubic_volume}%"
                    left-margin: 10
              type == "sink" && muted:
                - string:
                    text: 
                - string:
                    text: "{cubic_volume}%"
                    left-margin: 10

    - network:
        content:
          map:
            default:
              empty: {}
            conditions:
              type == ether && state == up:
                - string:
                    text: 󰈀
                - string:
                    text: "Ethernet"
                    left-margin: 8

    - network:
        poll-interval: 1000
        content:
          map:
            default:
              empty: {}
            conditions:
              type == wlan && state == up:
                - ramp:
                    tag: quality
                    items:
                      - string:
                          text: 󰤯
                      - string:
                          text: 󰤟
                      - string:
                          text: 󰤢
                      - string:
                          text: 󰤨
                - string:
                    text: "Wifi"
                    left-margin: 8

    - battery:
        name: BAT0
        <<: *battery

    - battery:
        name: BAT1
        <<: *battery
