"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[opener]
open = [{ run = 'nohup xdg-open "$1" > /dev/null 2>&1 &', desc = "Open" }]

[input]
cursor_blink = true
