require("plugins")

require("autocmds")
require("commands")
require("diagnostics")
require("globals")
require("keybinds")
require("lsp")
require("options")
require("statuscolumn")
require("statusline")
