import = [
	"~/.config/alacritty/window.toml",
	"~/.config/alacritty/font.toml",
	"~/.config/alacritty/colors.toml",
	"~/.config/alacritty/selection.toml",
	"~/.config/alacritty/cursor.toml",
	"~/.config/alacritty/keybins.toml",
]
