[colors]
primary = { background = "#000000", foreground = "#A0A0A0" }
cursor = { text = "#000000", cursor = "#A0A0A0" }
vi_mode_cursor = { text = "#000000", cursor = "#A0A0A0" }
search.focused_match = { background = "#303030", foreground = "#A0A0A0" }
search.matches = { background = "#303030", foreground = "#A0A0A0" }
footer_bar = { background = "#000000", foreground = "#A0A0A0" }
hints.start = { background = "#A0A0A0", foreground = "#000000" }
hints.end = { background = "#707070", foreground = "#000000" }
line_indicator = { background = "#000000", foreground = "#A0A0A0" }
selection = { background = "#303030", text = "CellForeground" }
normal = { black = "#404040", blue = "#606060", cyan = "#808080", green = "#A0A0A0", magenta = "#404040", red = "#606060", white = "#808080", yellow = "#A0A0A0" }
bright = { black = "#404040", blue = "#606060", cyan = "#808080", green = "#A0A0A0", magenta = "#404040", red = "#606060", white = "#808080", yellow = "#A0A0A0" }
